/*
 * Ink & Quill - a Skyrim SKSE writing framework: the player writes in books in the
 * book menu, with quill, ink or blood, for any mod that gives the text a meaning.
 * Copyright (C) 2026 Zevick
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "Editor.h"
#include "LayoutTest.h"
#include "Settings.h"
#include "Strings.h"
#include "WritingMode.h"
#include "WritingTools.h"

#include <spdlog/sinks/basic_file_sink.h>

namespace {

    void OnMessage(SKSE::MessagingInterface::Message* msg)
    {
        if (!msg) return;
        switch (msg->type) {
        case SKSE::MessagingInterface::kDataLoaded:
            InkAndQuill::Settings::Load();
            InkAndQuill::Strings::Load();
            InkAndQuill::WritingMode::Detect();
            InkAndQuill::WritingTools::OnDataLoaded();
            if (InkAndQuill::WritingMode::IsOn()) {
                InkAndQuill::Editor::Register();
                InkAndQuill::LayoutTest::Register();
            }
            break;
        case SKSE::MessagingInterface::kPreLoadGame:
        case SKSE::MessagingInterface::kNewGame:
            InkAndQuill::Editor::Reset();
            break;
        default:
            break;
        }
    }

    void InitializeLog()
    {
        auto path = SKSE::log::log_directory();
        if (!path) return;
        *path /= "InkAndQuill.log"sv;
        auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(path->string(), true);
        auto log = std::make_shared<spdlog::logger>("global log"s, std::move(sink));
        log->set_level(spdlog::level::info);
        log->flush_on(spdlog::level::info);
        spdlog::set_default_logger(std::move(log));
        spdlog::set_pattern("[%H:%M:%S] [%l] %v"s);

        const auto* plugin = SKSE::PluginDeclaration::GetSingleton();
        SKSE::log::info("{} v{}", plugin->GetName(), plugin->GetVersion());
    }
}

// SKSEPlugin_Version and SKSEPlugin_Query are generated by add_commonlibsse_plugin
// (CMakeLists.txt); don't declare them here.

SKSE_PLUGIN_LOAD(const SKSE::LoadInterface* a_skse)
{
    InitializeLog();
    // log = false: InitializeLog set up our logger, and CommonLib's would replace it.
    SKSE::Init(a_skse, { .log = false });
    if (auto* messaging = SKSE::GetMessagingInterface(); !messaging || !messaging->RegisterListener(OnMessage)) {
        SKSE::log::error("Couldn't register for SKSE messages");
        return false;
    }
    return true;
}
